### ISSUE TITLE
具体该怎么写nginx的server段，进行反向代理呢？

### ISSUE THREAD

**Issue by briteming** [abersheeran/websocks#6]
wiki里面说：“在启动服务端后，应使用 nginx、caddy 等反向代理服务器进行反向代理”。
我使用nginx，那么具体该怎么写nginx的server段进行反向代理呢？
可否贴出这个server段？

**Comment by abersheeran** [comment]
我的 Nginx 配置如下，按照你自己的参数进行修改

```conf
server {  
    listen 443 ssl;  
    server_name websocks;  

    root html;  
    ssl_certificate   /path/to/websocks.pem;  
    ssl_certificate_key  /path/to/websocks.key;  
    ssl_session_timeout 5m;  

    location / {
        proxy_pass http://127.0.0.1:8765;     
        proxy_set_header Host $http_host;  
        proxy_http_version 1.1;  
        proxy_set_header Upgrade $http_upgrade;  
        proxy_set_header Connection "upgrade";  
    }  
}  
```

**Comment by briteming** [comment]
http://127.0.0.1:8765里的8765是什么端口？

**Comment by briteming** [comment]
其实我现在关心的是如何把命令：
websocks client --policy PROXY --server-url ws://myusername:mypassword@vps-public-ip:2146 127.0.0.1 3278里的ws变成wss? 因为我发现用你这个方法翻墙不够坚挺，有时会失败，估计是连接未加密的缘故

**Comment by abersheeran** [comment]
Nginx 可以反向代理 websocket 连接，为之配置 tls 证书从而可接受 wss 请求。
如何申请证书可以自行查询。另外很多博客把 tls 证书叫 https 证书，这两你可以认为是一个东西。

**Comment by abersheeran** [comment]
> 其实我现在关心的是如何把命令：
> websocks client --policy PROXY --server-url ws://myusername:mypassword@vps-public-ip:2146 127.0.0.1 3278里的ws变成wss? 因为我发现用你这个方法翻墙不够坚挺，有时会失败，估计是连接未加密的缘故

看这个:2146端口你应该是用客户端直连的服务端，这是不推荐的，最好用 Caddy 反向代理它，这样你也不用考虑如何上 wss 的问题了，Caddy 会自动帮你申请证书并配置。

**Comment by abersheeran** [comment]
> [http://127.0.0.1:8765里的8765是什么端口？](http://127.0.0.1:8765%E9%87%8C%E7%9A%848765%E6%98%AF%E4%BB%80%E4%B9%88%E7%AB%AF%E5%8F%A3%EF%BC%9F)

8765 是我运行的 websocks 服务端端口，你需要把它修改到自己的。

**Comment by briteming** [comment]
我运行：
websocks client --policy PROXY --server-url wss://myusername:mypassword@mydomain.com:3150 127.0.0.1 3278
这次彻底翻不了墙了。
怎么回事呢？

我的server段是：
server {
listen 3150 ssl;
server_name mydomain.com;
location / {
	proxy_pass	http://127.0.0.1:2146;
        proxy_set_header Host	   $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
ssl on;
ssl_certificate /root/.acme.sh/mydomain.com/fullchain.cer;
ssl_certificate_key /root/.acme.sh/mydomain.com/mydomain.com.key;
ssl_session_timeout 5m;
}

 谢谢回复

**Comment by abersheeran** [comment]
```
proxy_http_version 1.1;  
proxy_set_header Upgrade $http_upgrade;  
proxy_set_header Connection "upgrade";  
```
加上这三行。

**Comment by briteming** [comment]
真的可以了。thank u so much

**Comment by abersheeran** [comment]
记得 Star 😀

**Comment by briteming** [comment]
在哪里star

**Comment by abersheeran** [comment]
![image](https://user-images.githubusercontent.com/25364828/82124302-bd1ce280-97d0-11ea-9988-8eecfa8efc6c.png)
