### ISSUE TITLE
提示

### ISSUE THREAD

**Issue by Jinxqq** [abersheeran/websocks#7]
你好，你的账号abersheeran于9月30日在gitstar.com.cn互赞平台上设置了目标仓库：abersheeran/websocks。目前你的账号欠赞过多，请及时回赞，否则将进入失信名单，届时所有获赞将取消。

如需停止互赞，可在不欠赞的情况下关闭互赞开关。

**Comment by abersheeran** [comment]
试了试平台功能而已，那取消呗。
